### PR TITLE
Report bug when loading mesh.

### PR DESCRIPTION
**Pull request by jmirabel**
On some of the meshes on which I tried, there are some faces with two vertices, i.e. `face.mNumIndices == 2`. So there are not triangles and `face.mIndices[2]` is invalid.

This pull-request is not satisfactory but I'm not sure what would be better. @florent-lamiraux , @stonneau : Any idea/advice ?

### CODE REVIEW

**Comment by stonneau** [comment]
Where does the mesh come from ?
Considering that you can probably not do anything with such a model,
I'd simply throw an error rather that reporting the issue.

**Comment by jmirabel** [comment]
I think the mesh is a DAE exported from blender.

I agree an exception is probably better.

**Comment by stonneau** [comment]
This being said, I don't think exporting collada from blender works well.
I already encountered issues in the past

**Comment by jmirabel** [comment]
Actually, I opened the Collada file and the file contained both `polylist` and `lines` tags. The tag `lines` was causing problems.

**Pull request merged**
